[2024-03-14 22:41:55,824][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-03-14 22:41:55,824][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=100, round_timeout=None)
[2024-03-14 22:41:59,230][flwr][INFO] - Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'CPU': 6.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 8876097945.0, 'memory': 17752195892.0, 'node:__internal_head__': 1.0}
[2024-03-14 22:41:59,230][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
[2024-03-14 22:41:59,230][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
[2024-03-14 22:41:59,246][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2024-03-14 22:41:59,247][flwr][INFO] - Initializing global parameters
[2024-03-14 22:41:59,247][flwr][INFO] - Requesting initial parameters from one random client
[2024-03-14 22:42:04,308][flwr][INFO] - Received initial parameters from one random client
[2024-03-14 22:42:04,308][flwr][INFO] - Evaluating initial parameters
[2024-03-14 22:42:18,808][flwr][INFO] - initial parameters (loss, other metrics): 0.022917344689369203, {'accuracy': 22.55859375}
[2024-03-14 22:42:18,808][flwr][INFO] - FL starting
[2024-03-14 22:42:18,808][flwr][DEBUG] - fit_round 1: strategy sampled 5 clients (out of 10)
[2024-03-14 22:46:29,287][flwr][DEBUG] - fit_round 1 received 5 results and 0 failures
[2024-03-14 22:46:47,443][flwr][INFO] - fit progress: (1, 0.028529837280511856, {'accuracy': 31.4453125}, 268.63676570000007)
[2024-03-14 22:46:47,443][flwr][DEBUG] - evaluate_round 1: strategy sampled 5 clients (out of 10)
[2024-03-14 22:47:10,411][flwr][DEBUG] - evaluate_round 1 received 5 results and 0 failures
[2024-03-14 22:47:10,413][flwr][DEBUG] - fit_round 2: strategy sampled 5 clients (out of 10)
[2024-03-14 22:51:58,853][flwr][DEBUG] - fit_round 2 received 5 results and 0 failures
[2024-03-14 22:52:17,226][flwr][INFO] - fit progress: (2, 0.03435918088257313, {'accuracy': 38.76953125}, 598.4509217000004)
[2024-03-14 22:52:17,226][flwr][DEBUG] - evaluate_round 2: strategy sampled 5 clients (out of 10)
[2024-03-14 22:52:40,208][flwr][DEBUG] - evaluate_round 2 received 5 results and 0 failures
[2024-03-14 22:52:40,208][flwr][DEBUG] - fit_round 3: strategy sampled 5 clients (out of 10)
[2024-03-14 22:57:46,982][flwr][DEBUG] - fit_round 3 received 5 results and 0 failures
[2024-03-14 22:58:06,013][flwr][INFO] - fit progress: (3, 0.08036187115311623, {'accuracy': 40.625}, 947.2558014000006)
[2024-03-14 22:58:06,014][flwr][DEBUG] - evaluate_round 3: strategy sampled 5 clients (out of 10)
[2024-03-14 22:58:28,603][flwr][DEBUG] - evaluate_round 3 received 5 results and 0 failures
[2024-03-14 22:58:28,604][flwr][DEBUG] - fit_round 4: strategy sampled 5 clients (out of 10)
[2024-03-14 23:01:54,452][flwr][ERROR] - The actor died unexpectedly before finishing this task.
	class_name: DefaultActor
	actor_id: eb6c1dce9aec94ee62bebd7c01000000
	pid: 6908
	namespace: 8016e24a-7230-4c4e-854d-3fff769930c7
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[2024-03-14 23:01:54,452][flwr][WARNING] - Actor(eb6c1dce9aec94ee62bebd7c01000000) will be remove from pool.
[2024-03-14 23:01:54,465][flwr][ERROR] - Traceback (most recent call last):
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 315, in _fetch_future_result
    raise ex
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\worker.py", line 2526, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: DefaultActor
	actor_id: eb6c1dce9aec94ee62bebd7c01000000
	pid: 6908
	namespace: 8016e24a-7230-4c4e-854d-3fff769930c7
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

[2024-03-14 23:01:54,474][flwr][ERROR] - The actor died unexpectedly before finishing this task.
	class_name: DefaultActor
	actor_id: eb6c1dce9aec94ee62bebd7c01000000
	pid: 6908
	namespace: 8016e24a-7230-4c4e-854d-3fff769930c7
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[2024-03-14 23:01:57,499][flwr][ERROR] - The actor died unexpectedly before finishing this task.
	class_name: DefaultActor
	actor_id: 7fb6cd5659d48c0ee29b497801000000
	pid: 13000
	namespace: 8016e24a-7230-4c4e-854d-3fff769930c7
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[2024-03-14 23:01:57,514][flwr][WARNING] - Actor(7fb6cd5659d48c0ee29b497801000000) will be remove from pool.
[2024-03-14 23:01:57,514][flwr][ERROR] - Traceback (most recent call last):
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 315, in _fetch_future_result
    raise ex
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\worker.py", line 2526, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: DefaultActor
	actor_id: 7fb6cd5659d48c0ee29b497801000000
	pid: 13000
	namespace: 8016e24a-7230-4c4e-854d-3fff769930c7
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

[2024-03-14 23:01:57,523][flwr][ERROR] - The actor died unexpectedly before finishing this task.
	class_name: DefaultActor
	actor_id: 7fb6cd5659d48c0ee29b497801000000
	pid: 13000
	namespace: 8016e24a-7230-4c4e-854d-3fff769930c7
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
