[2024-03-14 21:48:04,675][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-03-14 21:48:04,675][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=100, round_timeout=None)
[2024-03-14 21:48:09,072][flwr][INFO] - Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'CPU': 6.0, 'object_store_memory': 9207376281.0, 'memory': 18414752564.0, 'node:127.0.0.1': 1.0, 'node:__internal_head__': 1.0}
[2024-03-14 21:48:09,072][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
[2024-03-14 21:48:09,073][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.25}
[2024-03-14 21:48:09,086][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 4 actors
[2024-03-14 21:48:09,086][flwr][INFO] - Initializing global parameters
[2024-03-14 21:48:09,091][flwr][INFO] - Requesting initial parameters from one random client
[2024-03-14 21:48:15,658][flwr][INFO] - Received initial parameters from one random client
[2024-03-14 21:48:15,695][flwr][INFO] - Evaluating initial parameters
[2024-03-14 21:48:40,919][flwr][INFO] - initial parameters (loss, other metrics): 0.02572070652246475, {'accuracy': 24.0234375}
[2024-03-14 21:48:40,920][flwr][INFO] - FL starting
[2024-03-14 21:48:40,990][flwr][DEBUG] - fit_round 1: strategy sampled 5 clients (out of 10)
[2024-03-14 21:49:43,491][flwr][ERROR] - Traceback (most recent call last):
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=9972, ip=127.0.0.1, actor_id=062d420ca3d6639aba395b2201000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001DD6AF76350>)
                  ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 207, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\client_scaffold.py", line 130, in fit
    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 265, in train_scaffold
    outputs = net(images)
              ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 117, in forward
    x = self.resnet(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
        ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\functional.py", line 2482, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 1.23 GiB is allocated by PyTorch, and 21.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=9972, ip=127.0.0.1, actor_id=062d420ca3d6639aba395b2201000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001DD6AF76350>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py", line 207, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\client.py", line 234, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\numpy_client.py", line 238, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\client_scaffold.py", line 130, in fit\n    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 265, in train_scaffold\n    outputs = net(images)\n              ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 117, in forward\n    x = self.resnet(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 285, in forward\n    return self._forward_impl(x)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 269, in _forward_impl\n    x = self.bn1(x)\n        ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py", line 175, in forward\n    return F.batch_norm(\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\functional.py", line 2482, in batch_norm\n    return torch.batch_norm(\n           ^^^^^^^^^^^^^^^^^\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 1.23 GiB is allocated by PyTorch, and 21.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n',)

[2024-03-14 21:49:43,495][flwr][ERROR] - Traceback (most recent call last):
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=9300, ip=127.0.0.1, actor_id=0e611c77c149579114f11d3501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x0000016F7F21DD90>)
                  ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 207, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\client_scaffold.py", line 130, in fit
    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 265, in train_scaffold
    outputs = net(images)
              ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 117, in forward
    x = self.resnet(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 274, in _forward_impl
    x = self.layer2(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 100, in forward
    identity = self.downsample(x)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\functional.py", line 2482, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 5.60 GiB is allocated by PyTorch, and 25.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=9300, ip=127.0.0.1, actor_id=0e611c77c149579114f11d3501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x0000016F7F21DD90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 7 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py", line 207, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\client.py", line 234, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\numpy_client.py", line 238, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\client_scaffold.py", line 130, in fit\n    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 265, in train_scaffold\n    outputs = net(images)\n              ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 117, in forward\n    x = self.resnet(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 285, in forward\n    return self._forward_impl(x)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 274, in _forward_impl\n    x = self.layer2(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\container.py", line 217, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 100, in forward\n    identity = self.downsample(x)\n               ^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\container.py", line 217, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py", line 175, in forward\n    return F.batch_norm(\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\functional.py", line 2482, in batch_norm\n    return torch.batch_norm(\n           ^^^^^^^^^^^^^^^^^\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 5.60 GiB is allocated by PyTorch, and 25.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n',)

[2024-03-14 21:49:43,496][flwr][ERROR] - Traceback (most recent call last):
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=9280, ip=127.0.0.1, actor_id=224afdc320366a64b0b79d0c01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000002A91AD95150>)
                  ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 207, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\client_scaffold.py", line 130, in fit
    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 265, in train_scaffold
    outputs = net(images)
              ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 117, in forward
    x = self.resnet(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 273, in _forward_impl
    x = self.layer1(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 93, in forward
    out = self.bn1(out)
          ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\functional.py", line 2482, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 4.60 GiB is free. Of the allocated memory 4.23 GiB is allocated by PyTorch, and 151.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=9280, ip=127.0.0.1, actor_id=224afdc320366a64b0b79d0c01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000002A91AD95150>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 3 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py", line 207, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\client.py", line 234, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\numpy_client.py", line 238, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\client_scaffold.py", line 130, in fit\n    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 265, in train_scaffold\n    outputs = net(images)\n              ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 117, in forward\n    x = self.resnet(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 285, in forward\n    return self._forward_impl(x)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 273, in _forward_impl\n    x = self.layer1(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\container.py", line 217, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 93, in forward\n    out = self.bn1(out)\n          ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py", line 175, in forward\n    return F.batch_norm(\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\functional.py", line 2482, in batch_norm\n    return torch.batch_norm(\n           ^^^^^^^^^^^^^^^^^\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 4.60 GiB is free. Of the allocated memory 4.23 GiB is allocated by PyTorch, and 151.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n',)

[2024-03-14 21:49:43,528][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=9972, ip=127.0.0.1, actor_id=062d420ca3d6639aba395b2201000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001DD6AF76350>)
                  ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 207, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\client_scaffold.py", line 130, in fit
    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 265, in train_scaffold
    outputs = net(images)
              ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 117, in forward
    x = self.resnet(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
        ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\functional.py", line 2482, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 1.23 GiB is allocated by PyTorch, and 21.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=9972, ip=127.0.0.1, actor_id=062d420ca3d6639aba395b2201000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001DD6AF76350>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py", line 207, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\client.py", line 234, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\numpy_client.py", line 238, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\client_scaffold.py", line 130, in fit\n    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 265, in train_scaffold\n    outputs = net(images)\n              ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 117, in forward\n    x = self.resnet(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 285, in forward\n    return self._forward_impl(x)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 269, in _forward_impl\n    x = self.bn1(x)\n        ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py", line 175, in forward\n    return F.batch_norm(\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\functional.py", line 2482, in batch_norm\n    return torch.batch_norm(\n           ^^^^^^^^^^^^^^^^^\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 1.23 GiB is allocated by PyTorch, and 21.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n',)
[2024-03-14 21:49:43,561][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=9300, ip=127.0.0.1, actor_id=0e611c77c149579114f11d3501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x0000016F7F21DD90>)
                  ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 207, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\client_scaffold.py", line 130, in fit
    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 265, in train_scaffold
    outputs = net(images)
              ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 117, in forward
    x = self.resnet(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 274, in _forward_impl
    x = self.layer2(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 100, in forward
    identity = self.downsample(x)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\functional.py", line 2482, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 5.60 GiB is allocated by PyTorch, and 25.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=9300, ip=127.0.0.1, actor_id=0e611c77c149579114f11d3501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x0000016F7F21DD90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 7 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py", line 207, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\client.py", line 234, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\numpy_client.py", line 238, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\client_scaffold.py", line 130, in fit\n    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 265, in train_scaffold\n    outputs = net(images)\n              ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 117, in forward\n    x = self.resnet(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 285, in forward\n    return self._forward_impl(x)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 274, in _forward_impl\n    x = self.layer2(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\container.py", line 217, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 100, in forward\n    identity = self.downsample(x)\n               ^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\container.py", line 217, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py", line 175, in forward\n    return F.batch_norm(\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\functional.py", line 2482, in batch_norm\n    return torch.batch_norm(\n           ^^^^^^^^^^^^^^^^^\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 0 bytes is free. Of the allocated memory 5.60 GiB is allocated by PyTorch, and 25.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n',)
[2024-03-14 21:49:43,589][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=9280, ip=127.0.0.1, actor_id=224afdc320366a64b0b79d0c01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000002A91AD95150>)
                  ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 207, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\client_scaffold.py", line 130, in fit
    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 265, in train_scaffold
    outputs = net(images)
              ^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\Documents\GitHub\FlowerYtTut\model.py", line 117, in forward
    x = self.resnet(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 273, in _forward_impl
    x = self.layer1(x)
        ^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torchvision\models\resnet.py", line 93, in forward
    out = self.bn1(out)
          ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\torch\nn\functional.py", line 2482, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 4.60 GiB is free. Of the allocated memory 4.23 GiB is allocated by PyTorch, and 151.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=9280, ip=127.0.0.1, actor_id=224afdc320366a64b0b79d0c01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000002A91AD95150>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smpoulio_local\miniconda3\envs\fresh_pyt\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 3 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py", line 207, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\client.py", line 234, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\flwr\\client\\numpy_client.py", line 238, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\client_scaffold.py", line 130, in fit\n    train_loss, train_acc = train_scaffold(self.model, self.trainloader, optim, epochs, self.device, server_cv, self.client_cv)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 265, in train_scaffold\n    outputs = net(images)\n              ^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\Documents\\GitHub\\FlowerYtTut\\model.py", line 117, in forward\n    x = self.resnet(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 285, in forward\n    return self._forward_impl(x)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 273, in _forward_impl\n    x = self.layer1(x)\n        ^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\container.py", line 217, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torchvision\\models\\resnet.py", line 93, in forward\n    out = self.bn1(out)\n          ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\module.py", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py", line 175, in forward\n    return F.batch_norm(\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\smpoulio_local\\miniconda3\\envs\\fresh_pyt\\Lib\\site-packages\\torch\\nn\\functional.py", line 2482, in batch_norm\n    return torch.batch_norm(\n           ^^^^^^^^^^^^^^^^^\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 11.00 GiB of which 4.60 GiB is free. Of the allocated memory 4.23 GiB is allocated by PyTorch, and 151.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n',)
